version: '3.8'
services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: jikmunn-university-management:latest
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - '5000:5000'
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    restart: unless-stopped

  web:
    image: nginx:latest
    ports:
      - '80:80'
